# Generated by Django 2.1.5 on 2019-01-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='RobinHood'),
        ),
    ]
