# Generated by Django 2.1.5 on 2019-01-24 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='description',
            field=models.TextField(default='Donation Description'),
        ),
    ]
