# Generated by Django 2.1.5 on 2019-01-24 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_donation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='item_condition',
            field=models.CharField(choices=[('REP', 'Repairable'), ('WOR', 'Working')], default='WOR', max_length=3),
        ),
    ]
